CREATE TABLE "GCG_3501_CUSTWIN_SEL"(
 "SOID" IDENTITY DEFAULT '0',
 "TYPE" INTEGER,
 "SEQUENCE" INTEGER NOT NULL ,
 "SELECTIONID" INTEGER NOT NULL ,
 "SELECTIONTEXT" VARCHAR(50),
 PRIMARY KEY ("SOID"),
 UNIQUE ("SOID"));

CREATE UNIQUE INDEX "PK_SOID" USING 0 ON "GCG_3501_CUSTWIN_SEL"("SOID");